---
name: Titanium.App
summary: The top level App module.  The App module is mainly used for accessing information about the application at runtime.
extends: Titanium.Module
since: "0.1"
methods:
  - name: getArguments
    summary: return the arguments passed to the application on startup as a dictionary
    platforms: [android, iphone, ipad]
    returns:
        type: Object
events:
  - name: proximity
    summary: fired when a proximity state changes
    properties:
      - name: state
        summary: the proximity state value
    platforms: [android, iphone, ipad]
  - name: resume
    summary: fired when an iOS application will enter the foreground due to iOS 4's multitasking.
        This does not include pauses due to notifications or calls. See
        [applicationWillEnterForeground](http://developer.apple.com/library/ios/#documentation/UIKit/Reference/UIApplication_Class/Reference/Reference.html#//apple_ref/doc/uid/TP40006728-CH3-SW108) for
        the exact behavior that triggers this event.
    platforms: [iphone, ipad]
  - name: resumed
    summary: fired when an iOS application will return to being the focus. This does include not
        only the events that trigger resume, but pauses due to notifications or calls. See
        [applicationDidBecomeActive](http://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/Reference/Reference.html#//apple_ref/doc/uid/TP40006786-CH3-SW10) for
        the exact behavior that triggers this event.
    platforms: [iphone, ipad]
  - name: pause
    summary: fired when an iOS application will stop being the focus. This does include not
        only the user leaving the application, but pauses due to notifications or calls. See
        [applicationWillResignActive](http://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/Reference/Reference.html#//apple_ref/doc/uid/TP40006786-CH3-SW10) for
        the exact behavior that triggers this event.
    platforms: [iphone, ipad]
properties:
  - name: copyright
    summary: the application's copyright
    type: String
    permission: read-only
  - name: description
    summary: the application's description
    type: String
    permission: read-only
  - name: guid
    summary: the application's globally unique id (this is system generated and consistent through all versions)
    type: String
    permission: read-only
  - name: id
    summary: the application's app id as specified in Titanium Developer or Titanium Studio
    type: String
    permission: read-only
  - name: idleTimerDisabled
    summary: property for controlling whether the phone screen will be locked on idle time. Can be set to true to disable the timer
    type: Boolean
    platforms: [iphone, ipad]
  - name: name
    summary: the application's name
    type: String
    permission: read-only
  - name: proximityDetection
    summary: a boolean to indicate whether proximity detection is enabled
    type: Boolean
    platforms: [iphone, ipad]
  - name: proximityState
    summary: the state of the device's proximity detector
    type: Number
    platforms: [iphone, ipad]
  - name: publisher
    summary: the application's publisher
    type: String
    permission: read-only
  - name: url
    summary: the application url
    type: String
    permission: read-only
  - name: version
    summary: the application's version
    type: String
    permission: read-only
