(function(api){
	// Interfaces
	Ti._5.EventDriven(api);	
	
	// Properties	
	Ti._5.member(api, 'ACTION_AIRPLANE_MODE_CHANGED');
	Ti._5.member(api, 'ACTION_ALL_APPS');
	Ti._5.member(api, 'ACTION_ANSWER');
	Ti._5.member(api, 'ACTION_ATTACH_DATA');
	Ti._5.member(api, 'ACTION_BATTERY_CHANGED');
	Ti._5.member(api, 'ACTION_BATTERY_LOW');
	Ti._5.member(api, 'ACTION_BATTERY_OKAY');
	Ti._5.member(api, 'ACTION_BOOT_COMPLETED');
	Ti._5.member(api, 'ACTION_BUG_REPORT');
	Ti._5.member(api, 'ACTION_CALL');
	Ti._5.member(api, 'ACTION_CALL_BUTTON');
	Ti._5.member(api, 'ACTION_CAMERA_BUTTON');
	Ti._5.member(api, 'ACTION_CHOOSER');
	Ti._5.member(api, 'ACTION_CLOSE_SYSTEM_DIALOGS');
	Ti._5.member(api, 'ACTION_CONFIGURATION_CHANGED');
	Ti._5.member(api, 'ACTION_CREATE_SHORTCUT');
	Ti._5.member(api, 'ACTION_DATE_CHANGED');
	Ti._5.member(api, 'ACTION_DEFAULT');
	Ti._5.member(api, 'ACTION_DELETE');
	Ti._5.member(api, 'ACTION_DEVICE_STORAGE_LOW');
	Ti._5.member(api, 'ACTION_DIAL');
	Ti._5.member(api, 'ACTION_EDIT');
	Ti._5.member(api, 'ACTION_GET_CONTENT');
	Ti._5.member(api, 'ACTION_GTALK_SERVICE_CONNECTED');
	Ti._5.member(api, 'ACTION_GTALK_SERVICE_DISCONNECTED');
	Ti._5.member(api, 'ACTION_HEADSET_PLUG');
	Ti._5.member(api, 'ACTION_INPUT_METHOD_CHANGED');
	Ti._5.member(api, 'ACTION_INSERT');
	Ti._5.member(api, 'ACTION_INSERT_OR_EDIT');
	Ti._5.member(api, 'ACTION_MAIN');
	Ti._5.member(api, 'ACTION_MANAGE_PACKAGE_STORAGE');
	Ti._5.member(api, 'ACTION_MEDIA_BAD_REMOVAL');
	Ti._5.member(api, 'ACTION_MEDIA_BUTTON');
	Ti._5.member(api, 'ACTION_MEDIA_CHECKING');
	Ti._5.member(api, 'ACTION_MEDIA_EJECT');
	Ti._5.member(api, 'ACTION_MEDIA_MOUNTED');
	Ti._5.member(api, 'ACTION_MEDIA_NOFS');
	Ti._5.member(api, 'ACTION_MEDIA_REMOVED');
	Ti._5.member(api, 'ACTION_MEDIA_SCANNER_FINISHED');
	Ti._5.member(api, 'ACTION_MEDIA_SCANNER_SCAN_FILE');
	Ti._5.member(api, 'ACTION_MEDIA_SCANNER_STARTED');
	Ti._5.member(api, 'ACTION_MEDIA_SHARED');
	Ti._5.member(api, 'ACTION_MEDIA_UNMOUNTABLE');
	Ti._5.member(api, 'ACTION_MEDIA_UNMOUNTED');
	Ti._5.member(api, 'ACTION_NEW_OUTGOING_CALL');
	Ti._5.member(api, 'ACTION_PACKAGE_ADDED');
	Ti._5.member(api, 'ACTION_PACKAGE_CHANGED');
	Ti._5.member(api, 'ACTION_PACKAGE_DATA_CLEARED');
	Ti._5.member(api, 'ACTION_PACKAGE_INSTALL');
	Ti._5.member(api, 'ACTION_PACKAGE_REMOVED');
	Ti._5.member(api, 'ACTION_PACKAGE_REPLACED');
	Ti._5.member(api, 'ACTION_PACKAGE_RESTARTED');
	Ti._5.member(api, 'ACTION_PICK');
	Ti._5.member(api, 'ACTION_PICK_ACTIVITY');
	Ti._5.member(api, 'ACTION_POWER_CONNECTED');
	Ti._5.member(api, 'ACTION_POWER_DISCONNECTED');
	Ti._5.member(api, 'ACTION_POWER_USAGE_SUMMARY');
	Ti._5.member(api, 'ACTION_PROVIDER_CHANGED');
	Ti._5.member(api, 'ACTION_REBOOT');
	Ti._5.member(api, 'ACTION_RUN');
	Ti._5.member(api, 'ACTION_SCREEN_OFF');
	Ti._5.member(api, 'ACTION_SCREEN_ON');
	Ti._5.member(api, 'ACTION_SEARCH');
	Ti._5.member(api, 'ACTION_SEARCH_LONG_PRESS');
	Ti._5.member(api, 'ACTION_SEND');
	Ti._5.member(api, 'ACTION_SENDTO');
	Ti._5.member(api, 'ACTION_SEND_MULTIPLE');
	Ti._5.member(api, 'ACTION_SET_WALLPAPER');
	Ti._5.member(api, 'ACTION_SHUTDOWN');
	Ti._5.member(api, 'ACTION_SYNC');
	Ti._5.member(api, 'ACTION_SYSTEM_TUTORIAL');
	Ti._5.member(api, 'ACTION_TIME_CHANGED');
	Ti._5.member(api, 'ACTION_TIME_TICK');
	Ti._5.member(api, 'ACTION_UID_REMOVED');
	Ti._5.member(api, 'ACTION_UMS_CONNECTED');
	Ti._5.member(api, 'ACTION_UMS_DISCONNECTED');
	Ti._5.member(api, 'ACTION_USER_PRESENT');
	Ti._5.member(api, 'ACTION_VIEW');
	Ti._5.member(api, 'ACTION_VOICE_COMMAND');
	Ti._5.member(api, 'ACTION_WALLPAPER_CHANGED');
	Ti._5.member(api, 'ACTION_WEB_SEARCH');
	Ti._5.member(api, 'CATEGORY_ALTERNATIVE');
	Ti._5.member(api, 'CATEGORY_BROWSABLE');
	Ti._5.member(api, 'CATEGORY_DEFAULT');
	Ti._5.member(api, 'CATEGORY_DEVELOPMENT_PREFERENCE');
	Ti._5.member(api, 'CATEGORY_EMBED');
	Ti._5.member(api, 'CATEGORY_FRAMEWORK_INSTRUMENTATION_TEST');
	Ti._5.member(api, 'CATEGORY_HOME');
	Ti._5.member(api, 'CATEGORY_INFO');
	Ti._5.member(api, 'CATEGORY_LAUNCHER');
	Ti._5.member(api, 'CATEGORY_MONKEY');
	Ti._5.member(api, 'CATEGORY_OPENABLE');
	Ti._5.member(api, 'CATEGORY_PREFERENCE');
	Ti._5.member(api, 'CATEGORY_SAMPLE_CODE');
	Ti._5.member(api, 'CATEGORY_SELECTED_ALTERNATIVE');
	Ti._5.member(api, 'CATEGORY_TAB');
	Ti._5.member(api, 'CATEGORY_TEST');
	Ti._5.member(api, 'CATEGORY_UNIT_TEST');
	Ti._5.member(api, 'DEFAULT_ALL');
	Ti._5.member(api, 'DEFAULT_LIGHTS');
	Ti._5.member(api, 'DEFAULT_SOUND');
	Ti._5.member(api, 'DEFAULT_VIBRATE');
	Ti._5.member(api, 'EXTRA_ALARM_COUNT');
	Ti._5.member(api, 'EXTRA_BCC');
	Ti._5.member(api, 'EXTRA_CC');
	Ti._5.member(api, 'EXTRA_DATA_REMOVED');
	Ti._5.member(api, 'EXTRA_DONT_KILL_APP');
	Ti._5.member(api, 'EXTRA_EMAIL');
	Ti._5.member(api, 'EXTRA_INTENT');
	Ti._5.member(api, 'EXTRA_KEY_EVENT');
	Ti._5.member(api, 'EXTRA_PHONE_NUMBER');
	Ti._5.member(api, 'EXTRA_REPLACING');
	Ti._5.member(api, 'EXTRA_SHORTCUT_ICON');
	Ti._5.member(api, 'EXTRA_SHORTCUT_ICON_RESOURCE');
	Ti._5.member(api, 'EXTRA_SHORTCUT_INTENT');
	Ti._5.member(api, 'EXTRA_SHORTCUT_NAME');
	Ti._5.member(api, 'EXTRA_STREAM');
	Ti._5.member(api, 'EXTRA_SUBJECT');
	Ti._5.member(api, 'EXTRA_TEMPLATE');
	Ti._5.member(api, 'EXTRA_TEXT');
	Ti._5.member(api, 'EXTRA_TITLE');
	Ti._5.member(api, 'EXTRA_UID');
	Ti._5.member(api, 'FILL_IN_ACTION');
	Ti._5.member(api, 'FILL_IN_CATEGORIES');
	Ti._5.member(api, 'FILL_IN_COMPONENT');
	Ti._5.member(api, 'FILL_IN_DATA');
	Ti._5.member(api, 'FILL_IN_PACKAGE');
	Ti._5.member(api, 'FLAG_ACTIVITY_BROUGHT_TO_FRONT');
	Ti._5.member(api, 'FLAG_ACTIVITY_CLEAR_TOP');
	Ti._5.member(api, 'FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET');
	Ti._5.member(api, 'FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS');
	Ti._5.member(api, 'FLAG_ACTIVITY_FORWARD_RESULT');
	Ti._5.member(api, 'FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY');
	Ti._5.member(api, 'FLAG_ACTIVITY_MULTIPLE_TASK');
	Ti._5.member(api, 'FLAG_ACTIVITY_NEW_TASK');
	Ti._5.member(api, 'FLAG_ACTIVITY_NO_HISTORY');
	Ti._5.member(api, 'FLAG_ACTIVITY_NO_USER_ACTION');
	Ti._5.member(api, 'FLAG_ACTIVITY_PREVIOUS_IS_TOP');
	Ti._5.member(api, 'FLAG_ACTIVITY_REORDER_TO_FRONT');
	Ti._5.member(api, 'FLAG_ACTIVITY_RESET_TASK_IF_NEEDED');
	Ti._5.member(api, 'FLAG_ACTIVITY_SINGLE_TOP');
	Ti._5.member(api, 'FLAG_AUTO_CANCEL');
	Ti._5.member(api, 'FLAG_CANCEL_CURRENT');
	Ti._5.member(api, 'FLAG_DEBUG_LOG_RESOLUTION');
	Ti._5.member(api, 'FLAG_FROM_BACKGROUND');
	Ti._5.member(api, 'FLAG_GRANT_READ_URI_PERMISSION');
	Ti._5.member(api, 'FLAG_GRANT_WRITE_URI_PERMISSION');
	Ti._5.member(api, 'FLAG_INSISTENT');
	Ti._5.member(api, 'FLAG_NO_CLEAR');
	Ti._5.member(api, 'FLAG_NO_CREATE');
	Ti._5.member(api, 'FLAG_ONE_SHOT');
	Ti._5.member(api, 'FLAG_ONGOING_EVENT');
	Ti._5.member(api, 'FLAG_ONLY_ALERT_ONCE');
	Ti._5.member(api, 'FLAG_RECEIVER_REGISTERED_ONLY');
	Ti._5.member(api, 'FLAG_SHOW_LIGHTS');
	Ti._5.member(api, 'FLAG_UPDATE_CURRENT');
	Ti._5.member(api, 'PENDING_INTENT_FOR_ACTIVITY');
	Ti._5.member(api, 'PENDING_INTENT_FOR_BROADCAST');
	Ti._5.member(api, 'PENDING_INTENT_FOR_SERVICE');
	Ti._5.member(api, 'PENDING_INTENT_MAX_VALUE');
	Ti._5.member(api, 'RESULT_CANCELED');
	Ti._5.member(api, 'RESULT_FIRST_USER');
	Ti._5.member(api, 'RESULT_OK');
	Ti._5.member(api, 'SCREEN_ORIENTATION_BEHIND');
	Ti._5.member(api, 'SCREEN_ORIENTATION_LANDSCAPE');
	Ti._5.member(api, 'SCREEN_ORIENTATION_NOSENSOR');
	Ti._5.member(api, 'SCREEN_ORIENTATION_PORTRAIT');
	Ti._5.member(api, 'SCREEN_ORIENTATION_SENSOR');
	Ti._5.member(api, 'SCREEN_ORIENTATION_UNSPECIFIED');
	Ti._5.member(api, 'SCREEN_ORIENTATION_USER');
	Ti._5.member(api, 'STREAM_DEFAULT');
	Ti._5.member(api, 'URI_INTENT_SCHEME');	
	
	// Methods
	api.createBroadcastIntent = function(){
		console.debug('Method "Titanium.Android.createBroadcastIntent" is not implemented yet.');
	};
	api.createIntent = function(){
		console.debug('Method "Titanium.Android.createIntent" is not implemented yet.');
	};
	api.createIntentChooser = function(){
		console.debug('Method "Titanium.Android.createIntentChooser" is not implemented yet.');
	};
	api.createNotification = function(){
		console.debug('Method "Titanium.Android.createNotification" is not implemented yet.');
	};
	api.createPendingIntent = function(){
		console.debug('Method "Titanium.Android.createPendingIntent" is not implemented yet.');
	};
	api.createService = function(){
		console.debug('Method "Titanium.Android.createService" is not implemented yet.');
	};
	api.createServiceIntent = function(){
		console.debug('Method "Titanium.Android.createServiceIntent" is not implemented yet.');
	};
	api.isServiceRunning = function(){
		console.debug('Method "Titanium.Android.isServiceRunning" is not implemented yet.');
	};
	api.startService = function(){
		console.debug('Method "Titanium.Android.startService" is not implemented yet.');
	};
	api.stopService = function(){
		console.debug('Method "Titanium.Android.stopService" is not implemented yet.');
	};
})(Ti._5.createClass('Titanium.Android'));