name: iOS Build
description: Installs required dependencies and then builds the iOS side of the SDK

inputs:
  node-version:
    description: The version of Node.js to use
    required: true

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Lint
      run: npm run lint:ios
      shell: bash

    - name: Build
      run: npm run build:ios
      shell: bash

    - name: Package build output
      run: >
        tar -czvf ios-build.tar.gz
        dist/tmp/common
        iphone/TitaniumKit/build/TitaniumKit.xcframework
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        name: ios-build
        retention-days: 1
        path: ios-build.tar.gz
