/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_appcelerator_kroll_runtime_v8_V8Runtime */

#ifndef _Included_org_appcelerator_kroll_runtime_v8_V8Runtime
#define _Included_org_appcelerator_kroll_runtime_v8_V8Runtime
#ifdef __cplusplus
extern "C" {
#endif
#undef org_appcelerator_kroll_runtime_v8_V8Runtime_MSG_INIT
#define org_appcelerator_kroll_runtime_v8_V8Runtime_MSG_INIT 100L
#undef org_appcelerator_kroll_runtime_v8_V8Runtime_MSG_DISPOSE
#define org_appcelerator_kroll_runtime_v8_V8Runtime_MSG_DISPOSE 101L
#undef org_appcelerator_kroll_runtime_v8_V8Runtime_MSG_RUN_MODULE
#define org_appcelerator_kroll_runtime_v8_V8Runtime_MSG_RUN_MODULE 102L
#undef org_appcelerator_kroll_runtime_v8_V8Runtime_MSG_EVAL_STRING
#define org_appcelerator_kroll_runtime_v8_V8Runtime_MSG_EVAL_STRING 103L
#undef org_appcelerator_kroll_runtime_v8_V8Runtime_MSG_LAST_ID
#define org_appcelerator_kroll_runtime_v8_V8Runtime_MSG_LAST_ID 202L
#undef org_appcelerator_kroll_runtime_v8_V8Runtime_DONT_INTERCEPT
#define org_appcelerator_kroll_runtime_v8_V8Runtime_DONT_INTERCEPT -2147483647L
#undef org_appcelerator_kroll_runtime_v8_V8Runtime_DEFAULT_THREAD_STACK_SIZE
#define org_appcelerator_kroll_runtime_v8_V8Runtime_DEFAULT_THREAD_STACK_SIZE 16384L
#undef org_appcelerator_kroll_runtime_v8_V8Runtime_MSG_PROCESS_DEBUG_MESSAGES
#define org_appcelerator_kroll_runtime_v8_V8Runtime_MSG_PROCESS_DEBUG_MESSAGES 302L
#undef org_appcelerator_kroll_runtime_v8_V8Runtime_MAX_V8_IDLE_INTERVAL
#define org_appcelerator_kroll_runtime_v8_V8Runtime_MAX_V8_IDLE_INTERVAL 30000L
/*
 * Class:     org_appcelerator_kroll_runtime_v8_V8Runtime
 * Method:    nativeInit
 * Signature: (ZIZ)V
 */
JNIEXPORT void JNICALL Java_org_appcelerator_kroll_runtime_v8_V8Runtime_nativeInit
  (JNIEnv *, jobject, jboolean, jint, jboolean);

/*
 * Class:     org_appcelerator_kroll_runtime_v8_V8Runtime
 * Method:    nativeRunModule
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lorg/appcelerator/kroll/KrollProxySupport;)V
 */
JNIEXPORT void JNICALL Java_org_appcelerator_kroll_runtime_v8_V8Runtime_nativeRunModule
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     org_appcelerator_kroll_runtime_v8_V8Runtime
 * Method:    nativeEvalString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_appcelerator_kroll_runtime_v8_V8Runtime_nativeEvalString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_appcelerator_kroll_runtime_v8_V8Runtime
 * Method:    nativeProcessDebugMessages
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_appcelerator_kroll_runtime_v8_V8Runtime_nativeProcessDebugMessages
  (JNIEnv *, jobject);

/*
 * Class:     org_appcelerator_kroll_runtime_v8_V8Runtime
 * Method:    nativeIdle
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_appcelerator_kroll_runtime_v8_V8Runtime_nativeIdle
  (JNIEnv *, jobject);

/*
 * Class:     org_appcelerator_kroll_runtime_v8_V8Runtime
 * Method:    nativeDispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_appcelerator_kroll_runtime_v8_V8Runtime_nativeDispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
