/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.modules.titanium.___PROJECTNAME___;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;

import org.appcelerator.titanium.TiBlob;
import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.TiProxy;
import org.appcelerator.titanium.util.TiConfig;
import org.appcelerator.titanium.util.TiConvert;

// Import the minimal set of your namespaces here

public class __PROJECT_SHORT_NAME__Proxy extends TiProxy
{
	// Standard Debugging variables
	private static final String LCAT = "__PROJECT_SHORT_NAME__Proxy";
	private static final boolean DBG = TiConfig.LOGD;

	// Constructor
	public __PROJECT_SHORT_NAME__Proxy(TiContext tiContext, Object[] args) {
		super(tiContext);
	}
	
	// Put your own methods here
	
	

}