/**
e * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.modules.titanium.___PROJECTNAME___;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiBlob;
import org.appcelerator.titanium.TiDict;
import org.appcelerator.titanium.TiProxy;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;
import org.appcelerator.titanium.util.TiConvert;

public class Ti__PROJECT_SHORT_NAME__
{
	// Standard Debugging variables
	private static final String LCAT = "Ti__PROJECT_SHORT_NAME__";
	private static final boolean DBG = TiConfig.LOGD;

	private TiProxy proxy;

	public Ti__PROJECT_SHORT_NAME__(TiProxy proxy)
	{
		this.proxy = proxy;
	}

}