/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_appcelerator_kroll_runtime_Assets */

#ifndef _Included_org_appcelerator_kroll_runtime_Assets
#define _Included_org_appcelerator_kroll_runtime_Assets
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_appcelerator_kroll_runtime_Assets
 * Method:    assign
 * Signature: (Lorg/appcelerator/kroll/runtime/Assets;)V
 */
JNIEXPORT void JNICALL Java_org_appcelerator_kroll_runtime_Assets_assign
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
