/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package __MODULE_ID__.___PROJECTNAME___;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;

import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiBlob;
import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.util.TiConfig;
import org.appcelerator.titanium.util.TiConvert;

// Import the minimal set of your namespaces here

@Kroll.proxy
public class ___MODULE_NAME_CAMEL___Proxy extends KrollProxy
{
	// Standard Debugging variables
	private static final String LCAT = "___MODULE_NAME_CAMEL___Proxy";
	private static final boolean DBG = TiConfig.LOGD;

	protected Ti___MODULE_NAME_CAMEL___ ___PROJECT_SHORT_NAME___;
	
	// Constructor
	public ___MODULE_NAME_CAMEL___Proxy(TiContext tiContext) {
		super(tiContext);
		
		___PROJECT_SHORT_NAME___ = new Ti___MODULE_NAME_CAMEL___(this);
	}
	
	// Methods
	// You can define methods with @Kroll.method, for example:
	// @Kroll.method public void helloWorld() { Log.d(LCAT, "hello world!"); }
	

}