/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package __MODULE_ID__.___PROJECTNAME___;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.util.TiConfig;

/*import org.appcelerator.titanium.annotations.manifest.Ti;
import org.appcelerator.titanium.annotations.manifest.Ti.version;
import org.appcelerator.titanium.annotations.manifest.Ti.manifest.activity.configChangesTypes;
import org.appcelerator.titanium.annotations.manifest.Ti.manifest.activity.launchModeTypes;

@Ti.module(
		name = "__PROJECT_SHORT_NAME__", 
		version = @version(buildVersion=0, minorVersion=0, majorVersion=1),
		dependsUponTitanium = @version(minorVersion=3, majorVersion=1)
)*/
@Kroll.module(name="___MODULE_NAME_CAMEL___")
public class ___MODULE_NAME_CAMEL___Module extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "___MODULE_NAME_CAMEL___Module";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public ___MODULE_NAME_CAMEL___Module(TiContext tiContext) {
		super(tiContext);
	}

	// Methods
	// You can define methods with @Kroll.method, for example:
	// @Kroll.method public void helloWorld() { Log.d(LCAT, "hello world!"); }
	
	// Properties
	// You can define properties @Kroll.getProperty and @Kroll.setProperty, for example:
	// @Kroll.getProperty public String getMessage() { return "hello world"; }
	
	// Standard helpers 
	// To log a message to logcat
	//    Log.e(LCAT, "Unable to create tmp file: " + e.getMessage(), e);

}
