/**
e * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package __MODULE_ID__.___PROJECTNAME___;

import org.appcelerator.kroll.KrollProxy;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiBlob;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;
import org.appcelerator.titanium.util.TiConvert;

public class Ti___MODULE_NAME_CAMEL___
{
	// Standard Debugging variables
	private static final String LCAT = "Ti___MODULE_NAME_CAMEL___";
	private static final boolean DBG = TiConfig.LOGD;

	private KrollProxy proxy;

	public Ti___MODULE_NAME_CAMEL___(KrollProxy proxy)
	{
		this.proxy = proxy;
	}

}