import os;

DefaultEnvironment(
	JAVACHDIR = 'bin/classes',
	ANDROIDSDK = '/opt/android-sdk',
	ANDROIDJAR = '$ANDROIDSDK/platforms/android-1.5/android.jar',
	ANDROIDAAPT = '$ANDROIDSDK/platforms/android-1.5/tools/aapt',
	ANDROIDDX = '$ANDROIDSDK/platforms/android-1.5/tools/dx',
	TITANIUMJAR = '../titanium/bin/titanium.jar',
	ANDROIDAPKBLDR = '$ANDROIDSDK/tools/apkbuilder',
	JAVACLASSPATH = '$ANDROIDJAR:../titanium/bin/titanium.jar',
)

Command(target = 'R.java', source = 'src',
	action = "$ANDROIDAAPT package -m -J $SOURCE -M AndroidManifest.xml -S res -I $ANDROIDJAR"
) 

Depends(target='R.class', dependency ='R.java')
Java(target = 'bin/classes', source = 'src')

Command(target = 'bin/classes.dex', source = 'bin/classes',
	action = "$ANDROIDDX --dex --output=$TARGET $SOURCE $TITANIUMJAR")

Command(target = 'bin/tidev.ap_', source = 'res',
	action = "$ANDROIDAAPT package -f -M AndroidManifest.xml -A assets -S $SOURCE -I $ANDROIDJAR -I $TITANIUMJAR -F $TARGET")

Command(target = 'bin/tidev-unsigned.apk', source = 'bin/tidev.ap_',
	action = "$ANDROIDAPKBLDR $TARGET -u -z $SOURCE -f bin/classes.dex -rf src -rj $TITANIUMJAR")
# Jar(target = 'bin/titanium.jar', source = 'bin/classes')

# aapt -f -M AndroidManifest.xml -S res -I android.jar -I titanium.jar -F tidev.apk
# Android(target = 'bin/app.jar', )
# AndroidR(target = 'src/package/R.java', source = 'src')


