//
// these are dynamic defines used by the Titanium JS compiler
//
// when compiling in a real project these are dynamically generated
// these defined here mainly for when running inside xcode
//

// MODULES

#define USE_TI_STREAM
#define USE_TI_CODEC
#define USE_TI_UTILS
#define USE_TI_XML
#define USE_TI_ACCELEROMETER
#define USE_TI_API
#define USE_TI_APP
#define USE_TI_CONTACTS
#define USE_TI_DATABASE
#define USE_TI_FACEBOOK
#define USE_TI_FILESYSTEM
#define USE_TI_GEOLOCATION
#define USE_TI_GESTURE
#define USE_TI_MAP
#define USE_TI_MEDIA
#define USE_TI_NETWORK
#define USE_TI_NETWORKSOCKET
#define USE_TI_PLATFORM
#define USE_TI_YAHOO
#define USE_TI_UI
#define USE_TI_UITAB
#define USE_TI_UILABEL
#define USE_TI_UIBUTTON
#define USE_TI_UIPROGRESSBAR
#define USE_TI_UISEARCHBAR
#define USE_TI_UIACTIVITYINDICATOR
#define USE_TI_UISLIDER
#define USE_TI_UISWITCH
#define USE_TI_UIPICKER
#define USE_TI_UITOOLBAR //DEPRECATED
#define USE_TI_UITEXTAREA
#define USE_TI_UITEXTFIELD
#define USE_TI_UIIMAGEVIEW
#define USE_TI_UIMASKEDIMAGE
#define USE_TI_UIWEBVIEW
#define USE_TI_UIWINDOW
#define USE_TI_UIVIEW
#define USE_TI_UIOPTIONDIALOG
#define USE_TI_UIEMAILDIALOG
#define USE_TI_UIDASHBOARDVIEW
#define USE_TI_UISCROLLVIEW
#define USE_TI_UISCROLLABLEVIEW
#define USE_TI_UITABLEVIEW
#define USE_TI_UI2DMATRIX
#define USE_TI_UI3DMATRIX
#define USE_TI_UIANIMATION
#define USE_TI_UICOVERFLOWVIEW //DEPRECATED 
#define USE_TI_UITABBEDBAR //DEPRECATED

#define USE_TI_UIIPHONE
#define USE_TI_UIIPHONEROWANIMATIONSTYLE
#define USE_TI_UIIPHONESTATUSBAR
#define USE_TI_UIIPHONESYSTEMICON
#define USE_TI_UIIPHONESYSTEMBUTTONSTYLE
#define USE_TI_UIIPHONESYSTEMBUTTON
#define USE_TI_UIIPHONEACTIVITYINDICATORSTYLE
#define USE_TI_UIIPHONEANIMATIONSTYLE
#define USE_TI_UIIPHONEPROGRESSBARSTYLE
#define USE_TI_UIIPHONESCROLLINDICATORSTYLE
#define USE_TI_UIIPHONETABLEVIEWSTYLE
#define USE_TI_UIIPHONETABLEVIEWSEPARATORSTYLE
#define USE_TI_UIIPHONETABLEVIEWSCROLLPOSITION
#define USE_TI_UIIPHONETABLEVIEWCELLSELECTIONSTYLE
#define USE_TI_UIIPHONENAVIGATIONGROUP
#define USE_TI_UIIPHONEALERTDIALOGSTYLE

#define USE_TI_UICLIPBOARD

#define USE_TI_UIIPAD
#define USE_TI_UIIPADPOPOVER
#define USE_TI_UIIPADSPLITWINDOW
#define USE_TI_UIIPADDOCUMENTVIEWER
#define USE_TI_UIIPADSPLITWINDOWBUTTON

#define USE_TI_UIIOS
#define USE_TI_UIIOSADVIEW
#define USE_TI_UIIOS3DMATRIX
#define USE_TI_UIIOSCOVERFLOWVIEW
#define USE_TI_UIIOSTOOLBAR
#define USE_TI_UIIOSTABBEDBAR
#define USE_TI_UIIOSDOCUMENTVIEWER

#define USE_TI_APPIOS
