/**
 * Appcelerator Titanium Mobile
 * Copyright (c) 2015 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */

#ifndef Titanium_TiToJS_h
#define Titanium_TiToJS_h

#ifdef USE_JSCORE_FRAMEWORK

#import <JavaScriptCore/JavaScriptCore.h>


#define TiCheckScriptSyntax JSCheckScriptSyntax
#define TiClassCreate JSClassCreate
#define TiClassDefinition JSClassDefinition
#define TiClassRef JSClassRef
#define TiClassRelease JSClassRelease
#define TiClassRetain JSClassRetain
#define TiContextGetGlobalContext JSContextGetGlobalContext
#define TiContextGetGlobalObject JSContextGetGlobalObject
#define TiContextGetGroup JSContextGetGroup
#define TiContextGroupCreate JSContextGroupCreate
#define TiContextGroupRef JSContextGroupRef
#define TiContextGroupRelease JSContextGroupRelease
#define TiContextGroupRetain JSContextGroupRetain
#define TiContextRef JSContextRef
#define TiEvalScript JSEvaluateScript
#define TiGlobalContextCreate JSGlobalContextCreate
#define TiGlobalContextCreateInGroup JSGlobalContextCreateInGroup
#define TiGlobalContextRef JSGlobalContextRef
#define TiGlobalContextRelease JSGlobalContextRelease
#define TiGlobalContextRetain JSGlobalContextRetain
#define TiObjectCallAsConstructorCallback JSObjectCallAsConstructorCallback
#define TiObjectCallAsFunction JSObjectCallAsFunction
#define TiObjectCallAsFunctionCallback JSObjectCallAsFunctionCallback
#define TiObjectConvertToTypeCallback JSObjectConvertToTypeCallback
#define TiObjectCopyPropertyNames JSObjectCopyPropertyNames
#define TiObjectDeleteProperty JSObjectDeleteProperty
#define TiObjectFinalizeCallback JSObjectFinalizeCallback
#define TiObjectGetPrivate JSObjectGetPrivate
#define TiObjectGetProperty JSObjectGetProperty
#define TiObjectGetPropertyAtIndex JSObjectGetPropertyAtIndex
#define TiObjectHasInstanceCallback JSObjectHasInstanceCallback
#define TiObjectHasProperty JSObjectHasProperty
#define TiObjectInitializeCallback JSObjectInitializeCallback
#define TiObjectIsFunction JSObjectIsFunction
#define TiObjectMake JSObjectMake
#define TiObjectMakeArray JSObjectMakeArray
#define TiObjectMakeDate JSObjectMakeDate
#define TiObjectMakeError JSObjectMakeError
#define TiObjectMakeFunction JSObjectMakeFunction
#define TiObjectMakeFunctionWithCallback JSObjectMakeFunctionWithCallback
#define TiObjectRef JSObjectRef
#define TiObjectSetPrivate JSObjectSetPrivate
#define TiObjectSetProperty JSObjectSetProperty
#define TiObjectSetPropertyAtIndex JSObjectSetPropertyAtIndex
#define TiPropertyNameAccumulatorAddName JSPropertyNameAccumulatorAddName
#define TiPropertyNameAccumulatorRef JSPropertyNameAccumulatorRef
#define TiPropertyNameArrayGetCount JSPropertyNameArrayGetCount
#define TiPropertyNameArrayGetNameAtIndex JSPropertyNameArrayGetNameAtIndex
#define TiPropertyNameArrayRef JSPropertyNameArrayRef
#define TiPropertyNameArrayRef JSPropertyNameArrayRef
#define TiPropertyNameArrayRelease JSPropertyNameArrayRelease
#define TiStaticFunction JSStaticFunction
#define TiStaticValue JSStaticValue
#define TiStringCopyCFString JSStringCopyCFString
#define TiStringCreateWithCFString JSStringCreateWithCFString
#define TiStringCreateWithCharacters JSStringCreateWithCharacters
#define TiStringCreateWithUTF8CString JSStringCreateWithUTF8CString
#define TiStringGetCharactersPtr JSStringGetCharactersPtr
#define TiStringGetLength JSStringGetLength
#define TiStringGetMaximumUTF8CStringSize JSStringGetMaximumUTF8CStringSize
#define TiStringGetUTF8CString JSStringGetUTF8CString
#define TiStringIsEqual JSStringIsEqual
#define TiStringIsEqualToUTF8CString JSStringIsEqualToUTF8CString
#define TiStringRef JSStringRef
#define TiStringRelease JSStringRelease
#define TiStringRetain JSStringRetain
#define TiType JSType
#define TiValueCreateJSONString JSValueCreateJSONString
#define TiValueGetType JSValueGetType
#define TiValueIsBoolean JSValueIsBoolean
#define TiValueIsEqual JSValueIsEqual
#define TiValueIsInstanceOfConstructor JSValueIsInstanceOfConstructor
#define TiValueIsNull JSValueIsNull
#define TiValueIsNumber JSValueIsNumber
#define TiValueIsObject JSValueIsObject
#define TiValueIsObjectOfClass JSValueIsObjectOfClass
#define TiValueIsStrictEqual JSValueIsStrictEqual
#define TiValueIsString JSValueIsString
#define TiValueIsUndefined JSValueIsUndefined
#define TiValueMakeBoolean JSValueMakeBoolean
#define TiValueMakeFromJSONString JSValueMakeFromJSONString
#define TiValueMakeNull JSValueMakeNull
#define TiValueMakeNumber JSValueMakeNumber
#define TiValueMakeString JSValueMakeString
#define TiValueMakeUndefined JSValueMakeUndefined
#define TiValueProtect JSValueProtect
#define TiValueRef JSValueRef
#define TiValueToBoolean JSValueToBoolean
#define TiValueToNumber JSValueToNumber
#define TiValueToObject JSValueToObject
#define TiValueToStringCopy JSValueToStringCopy
#define TiValueToStringCopy JSValueToStringCopy
#define TiValueUnprotect JSValueUnprotect
#define kTITypeBoolean kJSTypeBoolean
#define kTITypeNull kJSTypeNull
#define kTITypeNumber kJSTypeNumber
#define kTITypeObject kJSTypeObject
#define kTITypeString kJSTypeString
#define kTITypeUndefined kJSTypeUndefined
#define kTiClassDefinitionEmpty kJSClassDefinitionEmpty
#define kTiPropertyAttributeDontDelete kJSPropertyAttributeDontDelete
#define kTiPropertyAttributeDontEnum kJSPropertyAttributeDontEnum
#define kTiPropertyAttributeNone kJSPropertyAttributeNone
#define kTiPropertyAttributeReadOnly kJSPropertyAttributeReadOnly

#else
#import "JavaScriptCore/TiCore.h"
#endif

#endif
