/*

 Titanium Cloud Module

 This module is used across three distinct platforms (iOS, Android, and Mobile Web), each with their own architectural
 demands upon it.

 Appcelerator Titanium is Copyright (c) 2009-2010 by Appcelerator, Inc.
 and licensed under the Apache Public License (version 2)

 Copyright 2008 Netflix, Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 A JavaScript implementation of the Secure Hash Algorithm, SHA-1, as defined
 in FIPS PUB 180-1
 Version 2.1a Copyright Paul Johnston 2000 - 2002.
 Other contributors: Greg Holt, Andrew Kepert, Ydnar, Lostinet
 Distributed under the BSD License
 See http://pajhome.org.uk/crypt/md5 for details.
*/
"mobileweb"==Ti.Platform.osname?define([],function(){return defineCloud({})}):defineCloud(exports);
function defineCloud(o){function x(r,g,f){if(void 0===g)throw"Argument "+r+" was not provided!";if(typeof g!=f)throw"Argument "+r+" was an unexpected type! Expected: "+f+", Received: "+typeof g;}function t(r,g){x("data",r,"object");x("callback",g,"function");y(this);this.url||(this.url=this.restNamespace+"/"+this.restMethod+".json");var f=void 0==o.useSecure?!0:o.useSecure;o.debug&&Ti.API.info('ACS Request: { url: "'+this.url+'", verb: "'+this.verb+'", secure: '+(f?"YES":"NO")+", data: "+JSON.stringify(r)+
" })");w.send(this.url,this.verb,r,f,function(h){if(g){var f=h.response;f||(f={});h.meta&&"ok"==h.meta.status?(f.success=!0,f.error=!1,f.meta=h.meta,o.debug&&Ti.API.info(JSON.stringify(f))):(f.success=!1,f.error=!0,f.code=h.meta?h.meta.code:h.statusCode,f.message=h.meta?h.meta.message:h.message||h.statusText,o.debug&&Ti.API.error(f.code+": "+f.message));g(f)}})}function k(){t.call(this,2==arguments.length?arguments[0]:{},2==arguments.length?arguments[1]:arguments[0])}function z(r){t.call(this,{},
r)}function y(r){r.restNamespace||(r.restNamespace=r.property.toLowerCase());r.restMethod||(r.restMethod=r.method.toLowerCase())}var p={PROPERTY_TYPE_ONLY_LATEST:0,PROPERTY_TYPE_SLASH_COMBINE:1,PROPERTY_TYPE_IGNORE:2};p.build=function g(f,h){var o=h.children||[],k;for(k in o)if(o.hasOwnProperty(k)){var l=o[k],e=l.propertyTypes||h.propertyTypes||{};e.children=p.PROPERTY_TYPE_IGNORE;for(var q in h)if(h.hasOwnProperty(q))switch(e[q]||p.PROPERTY_TYPE_ONLY_LATEST){case p.PROPERTY_TYPE_ONLY_LATEST:l[q]=
void 0===l[q]?h[q]:l[q];break;case p.PROPERTY_TYPE_SLASH_COMBINE:var u=[];h[q]&&u.push(h[q]);l[q]&&u.push(l[q]);l[q]=u.join("/")}l.method&&!l.children?f[l.method]=function(e){return function(){return e.executor.apply(e,arguments)}}(l):l.property&&g(f[l.property]={},l)}};p.build(o,{verb:"GET",executor:t,children:[{method:"hasStoredSession",executor:function(){return w.hasStoredSession()}},{method:"retrieveStoredSession",executor:function(){return w.retrieveStoredSession()}},{property:"Chats",children:[{method:"create",
verb:"POST"},{method:"query"},{method:"getChatGroups",restMethod:"get_chat_groups",executor:k}]},{property:"Checkins",children:[{method:"create",verb:"POST"},{method:"query",executor:k},{method:"show"},{method:"remove",restMethod:"delete",verb:"DELETE"}]},{property:"Clients",children:[{method:"geolocate",executor:k}]},{property:"Objects",executor:function(g,f){var h;g&&"object"==typeof g&&(x("data.classname",g.classname,"string"),y(this),this.url=this.restNamespace+"/"+g.classname+"/"+this.restMethod+
".json",h=g.classname,delete g.classname);t.call(this,g,f);g.classname=h},children:[{method:"create",verb:"POST"},{method:"show"},{method:"update",verb:"PUT"},{method:"remove",restMethod:"delete",verb:"DELETE"},{method:"query"}]},{property:"Emails",restNamespace:"custom_mailer",children:[{method:"send",verb:"POST",restMethod:"email_from_template"}]},{property:"KeyValues",children:[{method:"set",verb:"PUT"},{method:"get"},{method:"append",verb:"PUT"},{method:"increment",restMethod:"incrby",verb:"PUT"},
{method:"remove",restMethod:"delete",verb:"DELETE"}]},{property:"Photos",children:[{method:"create",verb:"POST"},{method:"show"},{method:"search"},{method:"query",executor:k},{method:"update",verb:"PUT"},{method:"remove",restMethod:"delete",verb:"DELETE"}]},{property:"PhotoCollections",restNamespace:"collections",children:[{method:"create",verb:"POST"},{method:"show"},{method:"update",verb:"PUT"},{method:"search"},{method:"showSubcollections",restMethod:"show/subcollections"},{method:"showPhotos",
restMethod:"show/photos"},{method:"remove",restMethod:"delete",verb:"DELETE"}]},{property:"Places",children:[{method:"create",verb:"POST"},{method:"search",executor:k},{method:"show"},{method:"update",verb:"PUT"},{method:"remove",restMethod:"delete",verb:"DELETE"},{method:"query",executor:k}]},{property:"Posts",children:[{method:"create",verb:"POST"},{method:"show"},{method:"query",executor:k},{method:"update",verb:"PUT"},{method:"remove",restMethod:"delete",verb:"DELETE"}]},{property:"PushNotifications",
restNamespace:"push_notification",verb:"POST",children:[{method:"subscribe"},{method:"unsubscribe",verb:"DELETE"},{method:"notify"}]},{property:"Reviews",children:[{method:"create",verb:"POST"},{method:"show"},{method:"query"},{method:"update",verb:"PUT"},{method:"remove",restMethod:"delete",verb:"DELETE"}]},{property:"SocialIntegrations",restNamespace:"users",children:[{method:"externalAccountLogin",restMethod:"external_account_login",verb:"POST"},{method:"externalAccountLink",restMethod:"external_account_link",
verb:"POST"},{method:"externalAccountUnlink",restMethod:"external_account_unlink",verb:"DELETE"},{method:"searchFacebookFriends",restNamespace:"social",restMethod:"facebook/search_friends",executor:z}]},{property:"Statuses",children:[{method:"create",verb:"POST"},{method:"search"},{method:"query",executor:k}]},{property:"Users",children:[{method:"create",verb:"POST"},{method:"login",verb:"POST"},{method:"show"},{method:"showMe",restMethod:"show/me",executor:z},{method:"search",executor:k},{method:"query",
executor:k},{method:"update",verb:"PUT"},{method:"logout",executor:function(g){t.call(this,{},function(f){w.reset();g(f)})}},{method:"remove",restMethod:"delete",verb:"DELETE",executor:function(){var g=arguments;t.call(this,2==g.length?g[0]:{},function(f){w.reset();(2==g.length?g[1]:g[0])(f)})}},{method:"requestResetPassword",restMethod:"request_reset_password"}]}]});var w=function(){function g(a,d){a[d>>5]|=128<<24-d%32;a[(d+64>>9<<4)+15]=d;for(var b=Array(80),v=1732584193,e=-271733879,c=-1732584194,
i=271733878,g=-1009589776,j=0;j<a.length;j+=16){for(var h=v,l=e,k=c,o=i,q=g,n=0;80>n;n++){b[n]=16>n?a[j+n]:(b[n-3]^b[n-8]^b[n-14]^b[n-16])<<1|(b[n-3]^b[n-8]^b[n-14]^b[n-16])>>>31;var p=v<<5|v>>>27,t;t=20>n?e&c|~e&i:40>n?e^c^i:60>n?e&c|e&i|c&i:e^c^i;p=f(f(p,t),f(f(g,b[n]),20>n?1518500249:40>n?1859775393:60>n?-1894007588:-899497514));g=i;i=c;c=e<<30|e>>>2;e=v;v=p}v=f(v,h);e=f(e,l);c=f(c,k);i=f(i,o);g=f(g,q)}return[v,e,c,i,g]}function f(a,d){var b=(a&65535)+(d&65535);return(a>>16)+(d>>16)+(b>>16)<<16|
b&65535}function h(a){for(var d=[],b=(1<<u)-1,e=0;e<a.length*u;e+=u)d[e>>5]|=(a.charCodeAt(e/u)&b)<<32-u-e%32;return d}function k(a,d,b){d?(this.oauthKey=a,this.oauthSecret=d):this.appKey=a;this.apiBaseURL=b?b:c.acs.sdk.url.baseURL;return this}function t(a,d){var b,e="production"==Ti.App.deployType.toLowerCase()?"production":"development";return(b=Ti.App.Properties.getString(a+"-"+e))&&"undefined"!=b||(b=Ti.App.Properties.getString(a))&&"undefined"!=b?b:d}var l={},e;null==e&&(e={});e.setProperties=
function(a,d){if(null!=a&&null!=d)for(var b in d)a[b]=d[b];return a};e.setProperties(e,{percentEncode:function(a){if(null==a)return"";if(a instanceof Array){for(var d="";0<a.length;++a)""!=d&&(d+="&"),d+=e.percentEncode(a[0]);return d}a=encodeURIComponent(a);a=a.replace(/\!/g,"%21");a=a.replace(/\*/g,"%2A");a=a.replace(/\'/g,"%27");a=a.replace(/\(/g,"%28");return a=a.replace(/\)/g,"%29")},decodePercent:function(a){null!=a&&(a=a.replace(/\+/g," "));return decodeURIComponent(a)},getParameterList:function(a){if(null==
a)return[];if("object"!=typeof a)return e.decodeForm(a+"");if(a instanceof Array)return a;var d=[],b;for(b in a)d.push([b,a[b]]);return d},getParameterMap:function(a){if(null==a)return{};if("object"!=typeof a)return e.getParameterMap(e.decodeForm(a+""));if(a instanceof Array){for(var d={},b=0;b<a.length;++b){var c=a[b][0];void 0===d[c]&&(d[c]=a[b][1])}return d}return a},getParameter:function(a,d){if(a instanceof Array)for(var b=0;b<a.length;++b){if(a[b][0]==d)return a[b][1]}else return e.getParameterMap(a)[d];
return null},formEncode:function(a){for(var d="",a=e.getParameterList(a),b=0;b<a.length;++b){var c=a[b][1];null==c&&(c="");""!=d&&(d+="&");d+=e.percentEncode(a[b][0])+"="+e.percentEncode(c)}return d},decodeForm:function(a){for(var d=[],a=a.split("&"),b=0;b<a.length;++b){var c=a[b];if(""!=c){var m=c.indexOf("="),f;0>m?(f=e.decodePercent(c),c=null):(f=e.decodePercent(c.substring(0,m)),c=e.decodePercent(c.substring(m+1)));d.push([f,c])}}return d},setParameter:function(a,d,b){var c=a.parameters;if(c instanceof
Array){for(a=0;a<c.length;++a)c[a][0]==d&&(void 0===b?c.splice(a,1):(c[a][1]=b,b=void 0));void 0!==b&&c.push([d,b])}else c=e.getParameterMap(c),c[d]=b,a.parameters=c},setParameters:function(a,d){for(var b=e.getParameterList(d),c=0;c<b.length;++c)e.setParameter(a,b[c][0],b[c][1])},completeRequest:function(a,d){null==a.method&&(a.method="GET");var b=e.getParameterMap(a.parameters);null==b.oauth_consumer_key&&e.setParameter(a,"oauth_consumer_key",d.consumerKey||"");null==b.oauth_token&&null!=d.token&&
e.setParameter(a,"oauth_token",d.token);null==b.oauth_version&&e.setParameter(a,"oauth_version","1.0");null==b.oauth_timestamp&&e.setParameter(a,"oauth_timestamp",e.timestamp());null==b.oauth_nonce&&e.setParameter(a,"oauth_nonce",e.nonce(6));e.SignatureMethod.sign(a,d)},setTimestampAndNonce:function(a){e.setParameter(a,"oauth_timestamp",e.timestamp());e.setParameter(a,"oauth_nonce",e.nonce(6))},addToURL:function(a,d){newURL=a;if(null!=d){var b=e.formEncode(d);0<b.length&&(newURL=0>a.indexOf("?")?
newURL+"?":newURL+"&",newURL+=b)}return newURL},getAuthorizationHeader:function(a,d){for(var b='OAuth realm="'+e.percentEncode(a)+'"',c=e.getParameterList(d),m=0;m<c.length;++m){var f=c[m],i=f[0];0==i.indexOf("oauth_")&&(b+=","+e.percentEncode(i)+'="'+e.percentEncode(f[1])+'"')}return b},correctTimestamp:function(a){e.timeCorrectionMsec=1E3*a-(new Date).getTime()},timeCorrectionMsec:0,timestamp:function(){var a=(new Date).getTime()+e.timeCorrectionMsec;return Math.floor(a/1E3)},nonce:function(a){for(var d=
e.nonce.CHARS,b="",c=0;c<a;++c)var m=Math.floor(Math.random()*d.length),b=b+d.substring(m,m+1);return b}});e.nonce.CHARS="0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz";e.declareClass=function(a,d,b){var c=a[d];a[d]=b;if(null!=b&&null!=c)for(var e in c)"prototype"!=e&&(b[e]=c[e]);return b};e.declareClass(e,"SignatureMethod",function(){});e.setProperties(e.SignatureMethod.prototype,{sign:function(a){var d=this.getSignature(e.SignatureMethod.getBaseString(a));e.setParameter(a,"oauth_signature",
d);return d},initialize:function(a,d){var b;b=null!=d.accessorSecret&&9<a.length&&"-Accessor"==a.substring(a.length-9)?d.accessorSecret:d.consumerSecret;this.key=e.percentEncode(b)+"&"+e.percentEncode(d.tokenSecret)}});e.setProperties(e.SignatureMethod,{sign:function(a,d){var b=e.getParameterMap(a.parameters).oauth_signature_method;if(null==b||""==b)b="HMAC-SHA1",e.setParameter(a,"oauth_signature_method",b);e.SignatureMethod.newMethod(b,d).sign(a)},newMethod:function(a,d){var b=e.SignatureMethod.REGISTERED[a];
if(null!=b){var c=new b;c.initialize(a,d);return c}var b=Error("signature_method_rejected"),m="";for(c in e.SignatureMethod.REGISTERED)""!=m&&(m+="&"),m+=e.percentEncode(c);b.oauth_acceptable_signature_methods=m;throw b;},REGISTERED:{},registerMethodClass:function(a,d){for(var b=0;b<a.length;++b)e.SignatureMethod.REGISTERED[a[b]]=d},makeSubclass:function(a){var d=e.SignatureMethod,b=function(){d.call(this)};b.prototype=new d;b.prototype.getSignature=a;return b.prototype.constructor=b},getBaseString:function(a){var d=
a.action,b=d.indexOf("?");if(0>b)b=a.parameters;else for(var b=e.decodeForm(d.substring(b+1)),c=e.getParameterList(a.parameters),m=0;m<c.length;++m)b.push(c[m]);return e.percentEncode(a.method.toUpperCase())+"&"+e.percentEncode(e.SignatureMethod.normalizeUrl(d))+"&"+e.percentEncode(e.SignatureMethod.normalizeParameters(b))},normalizeUrl:function(a){var d=e.SignatureMethod.parseUri(a),a=d.protocol.toLowerCase(),b=d.authority.toLowerCase();if("http"==a&&80==d.port||"https"==a&&443==d.port){var c=b.lastIndexOf(":");
0<=c&&(b=b.substring(0,c))}(d=d.path)||(d="/");return a+"://"+b+d},parseUri:function(a){for(var d="source,protocol,authority,userInfo,user,password,host,port,relative,path,directory,file,query,anchor".split(","),a=/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@\/]*):?([^:@\/]*))?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/.exec(a),b={},c=14;c--;)b[d[c]]=a[c]||"";return b},normalizeParameters:function(a){if(null==a)return"";for(var d=e.getParameterList(a),a=[],b=0;b<d.length;++b){var c=
d[b];"oauth_signature"!=c[0]&&a.push([e.percentEncode(c[0])+" "+e.percentEncode(c[1]),c])}a.sort(function(a,b){return a[0]<b[0]?-1:a[0]>b[0]?1:0});d=[];for(b=0;b<a.length;++b)d.push(a[b][1]);return e.formEncode(d)}});e.SignatureMethod.registerMethodClass(["PLAINTEXT","PLAINTEXT-Accessor"],e.SignatureMethod.makeSubclass(function(){return this.key}));e.SignatureMethod.registerMethodClass(["HMAC-SHA1","HMAC-SHA1-Accessor"],e.SignatureMethod.makeSubclass(function(a){q="=";var d=this.key,b=h(d);16<b.length&&
(b=g(b,d.length*u));for(var c=Array(16),d=Array(16),e=0;16>e;e++)c[e]=b[e]^909522486,d[e]=b[e]^1549556828;a=g(c.concat(h(a)),512+a.length*u);a=g(d.concat(a),672);b="";for(d=0;d<4*a.length;d+=3){c=(a[d>>2]>>8*(3-d%4)&255)<<16|(a[d+1>>2]>>8*(3-(d+1)%4)&255)<<8|a[d+2>>2]>>8*(3-(d+2)%4)&255;for(e=0;4>e;e++)b=8*d+6*e>32*a.length?b+q:b+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(c>>6*(3-e)&63)}return b}));var q="",u=8;k.prototype.sendRequest=function(a,d,b,f,g){var s=c.acs.js.sdk.utils.getAuthType(this);
if(s==c.acs.constants.unknown)g(c.acs.constants.noAppKeyError);else{var i="",i=f?i+c.acs.sdk.url.https:i+c.acs.sdk.url.http,i=i+(this.apiBaseURL+"/"+c.acs.sdk.url.version+"/"+a);s==c.acs.constants.app_key&&(i+=c.acs.constants.keyParam+this.appKey);b||(b={});d=d?d.toUpperCase():c.acs.constants.get_method;f=b;if(Ti.App.analytics){var h=f.analytics||{};h.id=Ti.Platform.createUUID();Ti.Platform.id&&(h.mid=Ti.Platform.id);h.aguid=Ti.App.guid;h.event="cloud."+a.replace(/\//g,".").replace(/\.json/,"");h.deploytype=
Ti.App.deployType||"development";h.sid=Ti.App.sessionId;f.ti_analytics=JSON.stringify(h)}b=c.acs.js.sdk.utils.cleanInvalidData(b);if(a=c.acs.js.sdk.utils.getFileObject(b)){try{var j;j=a.toString().match(/TiFilesystemFile/)?a.read():a;if(!j){g(c.acs.constants.fileLoadError);return}b[c.acs.constants.file]?(delete b[c.acs.constants.file],b[c.acs.constants.file]=j):b[c.acs.constants.photo]&&(delete b[c.acs.constants.photo],b[c.acs.constants.photo]=j)}catch(l){g(c.acs.constants.fileLoadError);return}j=
{};s==c.acs.constants.oauth&&(s={method:d,action:i,parameters:[]},c.acs.js.sdk.utils.populateOAuthParameters(s.parameters,this.oauthKey),e.completeRequest(s,{consumerSecret:this.oauthSecret}),"mobileweb"==Ti.Platform.osname?i+="?"+c.acs.js.sdk.utils.getOAuthParameters(s.parameters):j.Authorization=e.getAuthorizationHeader("",s.parameters))}else if(j={},s==c.acs.constants.oauth){var s={method:d,action:i,parameters:[]},k;for(k in b)b.hasOwnProperty(k)&&s.parameters.push([k,b[k]]);c.acs.js.sdk.utils.populateOAuthParameters(s.parameters,
this.oauthKey);e.completeRequest(s,{consumerSecret:this.oauthSecret});"mobileweb"==Ti.Platform.osname?i+="?"+c.acs.js.sdk.utils.getOAuthParameters(s.parameters):j.Authorization=e.getAuthorizationHeader("",s.parameters)}c.acs.js.sdk.utils.sendAppceleratorRequest(i,d,b,j,g)}};var c;c||(c={});c.acs||(c.acs={});c.acs.constants||(c.acs.constants={});c.acs.js||(c.acs.js={});c.acs.js.sdk||(c.acs.js.sdk={});c.acs.js.sdk.utils||(c.acs.js.sdk.utils={});c.acs.sdk||(c.acs.sdk={});c.acs.sdk.url||(c.acs.sdk.url=
{});c.acs.sdk.url.http="http://";c.acs.sdk.url.https="https://";c.acs.sdk.url.baseURL="api.cloud.appcelerator.com";c.acs.sdk.url.version="v1";c.acs.constants.app_key=1;c.acs.constants.oauth=2;c.acs.constants.unknown=-1;c.acs.constants.keyParam="?key=";c.acs.constants.file="file";c.acs.constants.photo="photo";c.acs.constants.noAppKeyError={meta:{status:"fail",code:409,message:"Application key is not provided."}};c.acs.constants.fileLoadError={meta:{status:"fail",code:400,message:"Unable to load file"}};
c.acs.js.sdk.utils.sessionId=null;c.acs.js.sdk.utils.retrieveSessionId=function(){null===c.acs.js.sdk.utils.sessionId&&(c.acs.js.sdk.utils.sessionId=Ti.App.Properties.getString("ACS-StoredSessionId"));return c.acs.js.sdk.utils.sessionId&&"undefined"!=c.acs.js.sdk.utils.sessionId?c.acs.js.sdk.utils.sessionId:null};c.acs.js.sdk.utils.storeSessionId=function(a){a&&(c.acs.js.sdk.utils.sessionId=a,Ti.App.Properties.setString("ACS-StoredSessionId",a))};c.acs.js.sdk.utils.clearSessionId=function(){c.acs.js.sdk.utils.sessionId=
!1;Ti.App.Properties.setString("ACS-StoredSessionId","")};c.acs.js.sdk.utils.getAuthType=function(a){if(a){if(a.appKey)return c.acs.constants.app_key;if(a.oauthKey&&a.oauthSecret)return c.acs.constants.oauth}return c.acs.constants.unknown};c.acs.js.sdk.utils.getFileObject=function(a){if(a)for(var d in a)if(a.hasOwnProperty(d)&&(d==c.acs.constants.photo||d==c.acs.constants.file))return a[d];return null};c.acs.js.sdk.utils.cleanInvalidData=function(a){if(a){for(var d in a)if(a.hasOwnProperty(d)){null==
a[d]&&delete a[d];if("object"==typeof a[d]){var b=JSON.stringify(a[d]);if("{}"==b)continue;if(a[d].nativePath)continue;a[d]=b}if(!0===a[d]||!1===a[d])a[d]=a[d]?1:0}return a}return{}};c.acs.js.sdk.utils.uploadMessageCallback=function(a){return a&&a.data?JSON.parse(a.data):{}};c.acs.js.sdk.utils.getOAuthParameters=function(a){var d="";if(a)for(var a=e.getParameterList(a),b=0;b<a.length;++b){var c=a[b],f=c[0];0==f.indexOf("oauth_")&&"oauth_token"!=f&&(d+="&"+e.percentEncode(f)+"="+e.percentEncode(c[1]))}0<
d.length&&(d=d.substring(1));return d};c.acs.js.sdk.utils.populateOAuthParameters=function(a,d){a&&d&&(a.push(["oauth_version","1.0"]),a.push(["oauth_consumer_key",d]),a.push(["oauth_signature_method","HMAC-SHA1"]),a.push(["oauth_nonce",e.nonce(15)]))};c.acs.js.sdk.utils.sendAppceleratorRequest=function(a,d,b,e,f){var g=Ti.Network.createHTTPClient({timeout:6E4,onsendstream:function(b){o.onsendstream&&o.onsendstream({url:a,progress:b.progress})},ondatastream:function(b){o.ondatastream&&o.ondatastream({url:a,
progress:b.progress})},onerror:function(a){var b={},d=this.responseText;try{var c=d;if(!c||0>=c.length)d=!1;else{for(var c=c.replace(/^\s\s*/,""),e=/\s/,g=c.length;e.test(c.charAt(--g)););d=c.slice(0,g+1)}d&&0<d.length&&(b=JSON.parse(d))}catch(h){b=h}b.message||(b.message=a.error);b.error=!0;b.statusText=this.statusText;b.status=this.status;b.meta&&(b.metaString=JSON.stringify(b.meta));f(b)},onload:function(){var a=JSON.parse(this.responseText);a&&a.meta&&(a.metaString=JSON.stringify(a.meta),c.acs.js.sdk.utils.storeSessionId(a.meta.session_id));
f(a)}}),i=a;switch(d.toUpperCase()){case "DELETE":case "GET":var h="",j;for(j in b)b.hasOwnProperty(j)&&(h+="&"+j+"="+encodeURI(b[j]));0<h.length&&(i=0<a.indexOf("?")?i+h:i+("?"+h.substring(1)),b={})}o.debug&&(Ti.API.info(d+": "+i),Ti.API.info("header: "+JSON.stringify(e)),Ti.API.info("data: "+JSON.stringify(b)));"mobileweb"==Ti.Platform.osname?(g._xhr.open(g.constants.connectionType=d,g.constants.location=i,!1),g._xhr.withCredentials="true"):g.open(d,i);g.setRequestHeader("Accept-Encoding","gzip,deflate");
if(e)for(j in e)e.hasOwnProperty(j)&&g.setRequestHeader(j,e[j]);(d=c.acs.js.sdk.utils.retrieveSessionId())&&g.setRequestHeader("Cookie","_session_id="+d);g.send(b)};var p=null;l.send=function(a,d,b,c,e){if(null==p){var f=t("acs-api-key",null),g=t("acs-base-url","api.cloud.appcelerator.com"),h=t("acs-oauth-key",null),j=t("acs-oauth-secret",null);if(h&&j)p=new k(h,j,g);else if(f)p=new k(f,null,g);else throw"ACS CREDENTIALS NOT SPECIFIED!";}p.sendRequest(a,d,b,c,e)};l.hasStoredSession=function(){return!!c.acs.js.sdk.utils.retrieveSessionId()};
l.retrieveStoredSession=function(){return c.acs.js.sdk.utils.retrieveSessionId()};l.reset=function(){c.acs.js.sdk.utils.clearSessionId();p=null};return l}();return o};